# Generated by Django 4.2.11 on 2024-03-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_point',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
