# Generated by Django 4.2.10 on 2024-03-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_tag_set'),
        ('weblog', '0005_tag_post_tag_set'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='tag_set',
            field=models.ManyToManyField(blank=True, related_name='weblog_post_set', related_query_name='weblog_post', to='blog.tag'),
        ),
    ]
