# Generated by Django 4.2.10 on 2024-03-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0006_delete_tag_alter_post_tag_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
