# Generated by Django 4.2.10 on 2024-03-08 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('rating', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
            ],
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': '포스팅', 'verbose_name_plural': '포스팅 목록'},
        ),
    ]
