# Generated by Django 4.2.10 on 2024-03-09 03:01

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='blog_tag_name_uniq',
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='blog_tag_name_uniq'),
        ),
    ]
