# Generated by Django 4.2.10 on 2024-03-10 11:00

from django.db import migrations, models
import django.db.models.deletion


def copy_relations(apps, schema_editor):
    Post = apps.get_model("blog", "Post")
    # 디폴트 M2M 관계 모델 클래스
    DefaultPostTagRelation = Post.tag_set.through
    # 새로운 M2M 관계에 사용할 모델 클래스
    NewPostTagRelation = apps.get_model("blog", "PostTagRelation")

    new_relation_list = []
    for relation in DefaultPostTagRelation.objects.all():
        # 외래키 필드를 참조하지 않고, 외래키 값을 참조하면 Post와 Tag에 대한 추가 쿼리가 없습니다.
        new_relation = NewPostTagRelation(
            post_id=relation.post_id,
            tag_id=relation.tag_id,
        )
        new_relation_list.append(new_relation)

    NewPostTagRelation.objects.bulk_create(new_relation_list, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_post_author_alter_post_tag_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.post"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.tag"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="posttagrelation",
            constraint=models.UniqueConstraint(
                fields=("post", "tag"), name="blog_post_tag_relation_unique"
            ),
        ),
        migrations.RunPython(
            copy_relations,
            migrations.RunPython.noop,
        ),
    ]
