# Generated by Django 4.2.10 on 2024-03-10 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_posttagrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag_set',
        ),
    ]
