# Generated by Django 4.2.10 on 2024-03-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hottrack', '0003_populate_song_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100),
        ),
    ]
